2025-06-16 03:15:35,409	INFO worker.py:1917 -- Started a local Ray instance.
[2m[36m(pid=2224072) [0m 0:   0%|          | 0.00/3.00 [00:00<?, ?it/s]                                                             [2m[36m(pid=2224072) [0m 0:  33%|â–ˆâ–ˆâ–ˆâ–Ž      | 1.00/3.00 [00:00<00:00, 1.51kit/s][2m[36m(pid=2224072) [0m 0: 10.0it [00:01, 7.85it/s]                           [2m[36m(pid=2224072) [0m 0: 10.0it [00:01, 7.85it/s][2m[36m(pid=2224072) [0m 0: 19.0it [00:02, 7.71it/s][2m[36m(pid=2224072) [0m 0: 19.0it [00:02, 7.71it/s][2m[36m(pid=2224072) [0m 0: 21.0it [00:03, 4.76it/s][2m[36m(pid=2224072) [0m 0: 21.0it [00:03, 4.76it/s]                                          [2m[36m(pid=2224072) [0m 0: 21.0it [00:03, 5.56it/s]
[Jun 16, 2025 03:16:03AM] No errors!
